{% set name = "starlite-multipart" %}
{% set version = "1.1.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/starlite-multipart-{{ version }}.tar.gz
  sha256: a8155a8f36bb3f2b335700cb46b91f5614e04ec49113f8894bbd834f5cbc7979

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - pip
    - poetry-core >=1.0.0
    - python >=3.6,<4.0
  run:
    - anyio
    - python >=3.6,<4.0

test:
  imports:
    - starlite_multipart
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/starlite-api/starlite-multipart
  doc_url: https://starlite-api.github.io/starlite-multipart/
  summary: Toolkit for working with multipart/formdata messages.
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - thewchan
